export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CORRECTION_REQUIRED = 'CORRECTION_REQUIRED',
  READY_FOR_INSPECTION = 'READY_FOR_INSPECTION',
  INSPECTION_FAILED = 'INSPECTION_FAILED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
