-- MPWT Vehicle Inspection Renewal Service
-- PostgreSQL constraint and index reference for the cumulative executed schema
-- after TypeORM migrations 1-12. This is documentation, not a migration script.
-- The TypeORM migrations remain the executable source of truth.

-- ---------------------------------------------------------------------------
-- Executed enum vocabularies
-- ---------------------------------------------------------------------------
-- user_role: CITIZEN, ADMIN, STAFF
-- user_status: PENDING_VERIFICATION, ACTIVE, DISABLED
-- vehicle_plate_category: PROVINCE, PERSONALIZED_CAMBODIA
-- vehicle_class: LIGHT, HEAVY
-- verification_purpose: REGISTER_ACCOUNT, RESET_PASSWORD, CHANGE_PHONE
-- application_status: DRAFT, SUBMITTED, UNDER_REVIEW, CORRECTION_REQUIRED,
--   APPOINTMENT_SELECTION_REQUIRED, APPROVED, REJECTED,
--   REINSPECTION_REQUIRED, INSPECTION_FAILED, CANCELLED, COMPLETED
-- document_type: VEHICLE_REGISTRATION_CARD,
--   PREVIOUS_INSPECTION_CERTIFICATE, CITIZEN_ID_CARD
-- document_status: PENDING, APPROVED, REJECTED
-- appointment_slot_status: OPEN, CLOSED, CANCELLED
-- appointment_status: SCHEDULED, COMPLETED, CANCELLED, NO_SHOW
-- inspection_status: PENDING, COMPLETED
-- inspection_result: PASS, FAIL
-- payment_method: PAY_AT_STATION, BANK_QR, BANK_CARD
-- payment_status: PENDING, CONFIRMED, FAILED, REJECTED
-- notification_type, notification_channel, notification_delivery_status,
-- timeline_event_type, and audit_actor_type also exist exactly as represented
-- in mpwt_vehicle_inspection_full_schema.dbml.

-- ---------------------------------------------------------------------------
-- CHECK constraints
-- ---------------------------------------------------------------------------
-- users.chk_users_phone_or_email
--   phone IS NOT NULL OR email IS NOT NULL
--
-- refresh_sessions.chk_refresh_sessions_token_hash_not_blank
--   btrim(token_hash) <> ''
-- refresh_sessions.chk_refresh_sessions_expires_after_created
--   expires_at > created_at
-- refresh_sessions.chk_refresh_sessions_last_used_after_created
--   last_used_at IS NULL OR last_used_at >= created_at
-- refresh_sessions.chk_refresh_sessions_revoked_after_created
--   revoked_at IS NULL OR revoked_at >= created_at
-- refresh_sessions.chk_refresh_sessions_reuse_detected_after_created
--   reuse_detected_at IS NULL OR reuse_detected_at >= created_at
-- refresh_sessions.chk_refresh_sessions_reuse_requires_revocation
--   reuse_detected_at IS NULL OR revoked_at IS NOT NULL
-- refresh_sessions.chk_refresh_sessions_revocation_reason_pair
--   (revoked_at IS NULL AND revocation_reason IS NULL)
--   OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)
--
-- vehicles.chk_vehicles_plate_province_category
--   (plate_category = 'PROVINCE' AND plate_province IS NOT NULL)
--   OR (plate_category = 'PERSONALIZED_CAMBODIA' AND plate_province IS NULL)
-- vehicles.chk_vehicles_classification_complete
--   vehicle_class, inspection_category_id, classification_verified_at, and
--   classification_verified_by are either all NULL or all non-NULL.
--
-- inspection_vehicle_categories.chk_vehicle_categories_code_not_blank
--   btrim(code) <> ''
-- inspection_vehicle_categories.chk_vehicle_categories_name_kh_not_blank
--   btrim(name_kh) <> ''
-- inspection_vehicle_categories.chk_vehicle_categories_validity_positive
--   validity_months > 0
-- inspection_vehicle_categories.chk_vehicle_categories_inspection_fee_nonnegative
--   inspection_fee_khr >= 0
-- inspection_vehicle_categories.chk_vehicle_categories_service_fee_nonnegative
--   service_fee_khr >= 0
--
-- vehicle_classification_history.chk_vehicle_class_history_previous_pair
--   previous_vehicle_class and previous_inspection_category_id are both NULL
--   or both non-NULL.
-- vehicle_classification_history.chk_vehicle_class_history_reason_not_blank
--   btrim(reason) <> ''
--
-- renewal_applications.chk_renewal_applications_current_rejection_reason
--   current_rejection_reason IS NULL OR
--   char_length(btrim(current_rejection_reason)) BETWEEN 1 AND 500
-- renewal_applications.chk_renewal_applications_preferred_inspection_selection_pair
--   preferred_inspection_station_id and preferred_inspection_date are both
--   NULL or both non-NULL.
--
-- renewal_application_status_history.chk_renewal_application_status_history_transition
--   (previous_status IS NULL AND new_status = 'DRAFT') OR
--   (previous_status IS NOT NULL AND previous_status <> new_status)
--
-- application_documents.chk_document_version
--   version_number > 0
-- application_documents.chk_document_file_size
--   file_size_bytes > 0
-- application_documents.chk_application_documents_file_size_max_5mb
--   file_size_bytes <= 5242880
--
-- appointment_slots.chk_appointment_slot_capacity
--   capacity > 0
-- appointment_slots.chk_appointment_slot_time
--   end_time > start_time
--
-- appointments.chk_appointments_slot_or_daily_capacity
--   (slot_id IS NOT NULL AND daily_capacity_id IS NULL) OR
--   (slot_id IS NULL AND daily_capacity_id IS NOT NULL)
--
-- payments.chk_payment_amounts
--   base_amount >= 0 AND late_fee >= 0 AND total_amount >= 0 AND
--   total_amount = base_amount + late_fee
-- payments.chk_payments_provider_name_required
--   provider_transaction_id IS NULL OR provider_name IS NOT NULL
-- payments.chk_payments_late_days_nonnegative
--   late_days >= 0
-- payments.chk_payments_inspection_fee_nonnegative
--   inspection_fee_khr >= 0
-- payments.chk_payments_service_fee_nonnegative
--   service_fee_khr >= 0
-- payments.chk_payments_base_amount_fee_components
--   base_amount = inspection_fee_khr + service_fee_khr
--
-- payment_status_history.chk_payment_status_history_status_transition
--   from_status <> to_status
--
-- stickers.chk_stickers_sticker_number_trimmed_nonempty
--   sticker_number = btrim(sticker_number) AND sticker_number <> ''
--
-- inspection_station_daily_capacities.chk_inspection_station_daily_capacities_daily_capacity
--   daily_capacity > 0
-- inspection_station_daily_capacities.chk_inspection_station_daily_capacities_reserved_count
--   reserved_count >= 0 AND reserved_count <= daily_capacity

-- ---------------------------------------------------------------------------
-- Unique constraints and unique indexes
-- ---------------------------------------------------------------------------
-- users: unique phone; unique email.
-- citizen_profiles: unique user_id; unique national_id_number.
-- vehicles: unique registration_number; unique chassis_number.
-- inspection_stations: unique code.
-- inspection_vehicle_categories.uq_inspection_vehicle_categories_code: code.
-- inspection_vehicle_categories.uq_inspection_vehicle_categories_id_class:
--   (id, vehicle_class).
-- renewal_applications: unique reference_number.
-- application_documents.uq_application_documents_application_document_type_version:
--   (application_id, document_type, version_number).
-- appointment_slots.uq_appointment_slots_station_date_start_end:
--   (station_id, slot_date, start_time, end_time).
-- appointments.uq_appointments_id_application: (id, application_id).
-- inspections: unique appointment_id.
-- payments: unique application_id; unique invoice_number; unique receipt_number.
-- stickers.uq_stickers_application: unique application_id.
-- stickers.uq_stickers_inspection: unique inspection_id.
-- stickers.uq_stickers_sticker_number: unique sticker_number.
-- inspection_station_daily_capacities.uq_inspection_station_daily_capacities_station_date:
--   (station_id, capacity_date).
--
-- uq_vehicles_province_plate_identity
--   unique (plate_province, plate_number)
--   where plate_category = 'PROVINCE'::vehicle_plate_category.
-- uq_vehicles_personalized_plate_number
--   unique (plate_number)
--   where plate_category = 'PERSONALIZED_CAMBODIA'::vehicle_plate_category.
-- uq_unfinished_application_per_vehicle
--   unique (vehicle_id) where status IN ('DRAFT', 'SUBMITTED',
--   'UNDER_REVIEW', 'CORRECTION_REQUIRED',
--   'APPOINTMENT_SELECTION_REQUIRED', 'APPROVED',
--   'REINSPECTION_REQUIRED')::application_status.
-- uq_current_document_per_type
--   unique (application_id, document_type) where is_current = true.
-- uq_scheduled_appointment_per_application
--   unique (application_id) where status = 'SCHEDULED'::appointment_status.
-- uq_provider_transaction
--   unique (provider_name, provider_transaction_id)
--   where provider_transaction_id IS NOT NULL.

-- ---------------------------------------------------------------------------
-- Non-unique indexes
-- ---------------------------------------------------------------------------
-- verification_codes.IDX_e2aa1f0c94500d4aa891eaf32f:
--   (destination, purpose, created_at)
-- refresh_sessions.idx_refresh_sessions_user_active:
--   (user_id, expires_at) where revoked_at IS NULL
-- refresh_sessions.idx_refresh_sessions_expires_at: (expires_at)
-- inspection_vehicle_categories.idx_inspection_vehicle_categories_class_active:
--   (vehicle_class, is_active)
-- vehicles.idx_vehicles_inspection_category_class:
--   (inspection_category_id, vehicle_class)
-- vehicle_classification_history.idx_vehicle_classification_history_vehicle_created:
--   (vehicle_id, created_at, id)
-- renewal_applications.idx_renewal_applications_status: (status)
-- renewal_applications.idx_renewal_applications_citizen_submitted_at:
--   (citizen_id, submitted_at)
-- renewal_applications.idx_renewal_applications_vehicle_submitted_at:
--   (vehicle_id, submitted_at)
-- renewal_applications.idx_renewal_applications_preferred_station_date:
--   (preferred_inspection_station_id, preferred_inspection_date)
-- renewal_application_status_history.idx_renewal_application_status_history_application_created:
--   (application_id, created_at, id)
-- application_documents.idx_application_documents_application_status:
--   (application_id, status)
-- appointment_slots.idx_appointment_slots_station_date_status:
--   (station_id, slot_date, status)
-- appointments.idx_appointments_application_status: (application_id, status)
-- appointments.idx_appointments_slot_status: (slot_id, status)
-- appointments.idx_appointments_daily_capacity_status:
--   (daily_capacity_id, status)
-- inspections.idx_inspections_application_created: (application_id, created_at)
-- inspections.idx_inspections_status: (status)
-- inspections.idx_inspections_result: (result)
-- payments.idx_payments_method: (method)
-- payments.idx_payments_status: (status)
-- payment_status_history.idx_payment_status_history_payment_created:
--   (payment_id, created_at)
-- payment_status_history.idx_payment_status_history_changed_by_user:
--   (changed_by_user_id)
-- stickers.idx_stickers_issued_at: (issued_at)
-- notifications.idx_notifications_application_created: (application_id, created_at)
-- notifications.idx_notifications_recipient_read_created:
--   (recipient_user_id, is_read, created_at)
-- application_timeline_events.idx_timeline_application_occurred:
--   (application_id, occurred_at)
-- application_timeline_events.idx_timeline_application_visible_occurred:
--   (application_id, visible_to_citizen, occurred_at)
-- audit_logs.idx_audit_logs_actor_created: (actor_user_id, created_at)
-- audit_logs.idx_audit_logs_entity_created: (entity_type, entity_id, created_at)
-- audit_logs.idx_audit_logs_application_created: (application_id, created_at)

-- ---------------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------------
-- The following FK names and actions are current. Each action not shown as
-- RESTRICT, SET NULL, or CASCADE is exactly the migration's ON UPDATE action.
--
-- application_documents.FK_9ad8ab815e842d67e9aaec900cb:
--   application_id -> renewal_applications(id), DELETE RESTRICT, UPDATE NO ACTION
-- application_documents.FK_d9af0254f7efae9da2693aa4742:
--   uploaded_by_user_id -> users(id), DELETE RESTRICT, UPDATE NO ACTION
-- application_documents.FK_0fe03681b334256703eb84219ba:
--   reviewed_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- application_documents.FK_5e03b1c78c991240bc4eae02183:
--   replaces_document_id -> application_documents(id), DELETE RESTRICT, UPDATE NO ACTION
-- audit_logs.FK_f160d97a931844109de9d04228f:
--   actor_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- audit_logs.FK_e64c07c384f813ed88b30316272:
--   application_id -> renewal_applications(id), DELETE SET NULL, UPDATE NO ACTION
-- verification_codes.FK_0a53c41a810420ee446082ce6c6:
--   user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- refresh_sessions.fk_refresh_sessions_user:
--   user_id -> users(id), DELETE CASCADE, UPDATE NO ACTION
-- citizen_profiles.FK_74180041ad4437e4b389830a81a:
--   user_id -> users(id), DELETE RESTRICT, UPDATE NO ACTION
-- vehicles.FK_2bbcffac87540842b672d79f3ba:
--   linked_citizen_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- vehicles.fk_vehicles_category_class:
--   (inspection_category_id, vehicle_class) ->
--   inspection_vehicle_categories(id, vehicle_class), DELETE RESTRICT, UPDATE RESTRICT
-- vehicles.fk_vehicles_classification_verified_by:
--   classification_verified_by -> users(id), DELETE RESTRICT, UPDATE RESTRICT
-- vehicle_classification_history.fk_vehicle_class_history_vehicle:
--   vehicle_id -> vehicles(id), DELETE RESTRICT, UPDATE RESTRICT
-- vehicle_classification_history.fk_vehicle_class_history_prev_category_class:
--   (previous_inspection_category_id, previous_vehicle_class) ->
--   inspection_vehicle_categories(id, vehicle_class), DELETE RESTRICT, UPDATE RESTRICT
-- vehicle_classification_history.fk_vehicle_class_history_new_category_class:
--   (new_inspection_category_id, new_vehicle_class) ->
--   inspection_vehicle_categories(id, vehicle_class), DELETE RESTRICT, UPDATE RESTRICT
-- vehicle_classification_history.fk_vehicle_class_history_changed_by_admin:
--   changed_by_admin_id -> users(id), DELETE RESTRICT, UPDATE RESTRICT
-- renewal_applications.FK_c84f3f2e9ec197ad80eb6a6f83d:
--   citizen_id -> users(id), DELETE RESTRICT, UPDATE NO ACTION
-- renewal_applications.FK_b3cb416fe563ac49b11f8bb4d8b:
--   vehicle_id -> vehicles(id), DELETE RESTRICT, UPDATE NO ACTION
-- renewal_applications.FK_557393d26f8ac9b03c84744e9bf:
--   cancelled_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- renewal_applications.fk_renewal_applications_preferred_inspection_station:
--   preferred_inspection_station_id -> inspection_stations(id), DELETE RESTRICT, UPDATE RESTRICT
-- renewal_application_status_history.fk_renewal_application_status_history_application:
--   application_id -> renewal_applications(id), DELETE RESTRICT, UPDATE RESTRICT
-- renewal_application_status_history.fk_renewal_application_status_history_changed_by:
--   changed_by_user_id -> users(id), DELETE RESTRICT, UPDATE RESTRICT
-- inspection_station_daily_capacities.fk_inspection_station_daily_capacities_station:
--   station_id -> inspection_stations(id), DELETE RESTRICT, UPDATE RESTRICT
-- appointment_slots.FK_89c035ca139f732036d4a648b9e:
--   station_id -> inspection_stations(id), DELETE RESTRICT, UPDATE NO ACTION
-- appointments.FK_ea1002cd0a41822ca930cb1c7e5:
--   application_id -> renewal_applications(id), DELETE RESTRICT, UPDATE NO ACTION
-- appointments.FK_b1ccdd43ac8ccbb787c68a64a13:
--   slot_id -> appointment_slots(id), DELETE RESTRICT, UPDATE NO ACTION
-- appointments.fk_appointments_daily_capacity:
--   daily_capacity_id -> inspection_station_daily_capacities(id), DELETE RESTRICT, UPDATE RESTRICT
-- appointments.FK_f989063890cd83f0e7652a5de45:
--   cancelled_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- appointments.FK_89c8373a12d9beae36102216b09:
--   no_show_marked_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- inspections.FK_f255b06d9aa8dfd89e147742723:
--   application_id -> renewal_applications(id), DELETE RESTRICT, UPDATE NO ACTION
-- inspections.FK_572ebcefff16193088f271b9d98:
--   appointment_id -> appointments(id), DELETE RESTRICT, UPDATE NO ACTION
-- inspections.fk_inspections_appointment_application:
--   (appointment_id, application_id) -> appointments(id, application_id), DELETE RESTRICT, UPDATE NO ACTION
-- inspections.FK_ad5e97202348d01c9ee4851b67d:
--   recorded_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- payments.FK_3b379ebb0e5d8ac17f998b932e7:
--   application_id -> renewal_applications(id), DELETE RESTRICT, UPDATE NO ACTION
-- payments.FK_d11985ac51d0104779148528b7b:
--   confirmed_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- payments.FK_9464a28484ff27338e4eb98dcb2:
--   rejected_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- payment_status_history.fk_payment_status_history_payment:
--   payment_id -> payments(id), DELETE RESTRICT, UPDATE RESTRICT
-- payment_status_history.fk_payment_status_history_changed_by_user:
--   changed_by_user_id -> users(id), DELETE SET NULL, UPDATE RESTRICT
-- stickers.fk_stickers_application:
--   application_id -> renewal_applications(id), DELETE RESTRICT, UPDATE NO ACTION
-- stickers.fk_stickers_inspection:
--   inspection_id -> inspections(id), DELETE RESTRICT, UPDATE NO ACTION
-- stickers.fk_stickers_issued_by_user:
--   issued_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- notifications.FK_2726bde496d82b6401532ab1477:
--   recipient_user_id -> users(id), DELETE RESTRICT, UPDATE NO ACTION
-- notifications.FK_dd75186e413a1f6e0d1ef8e1214:
--   application_id -> renewal_applications(id), DELETE SET NULL, UPDATE NO ACTION
-- notifications.FK_0af187ad618f397cf2a0e393276:
--   created_by_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION
-- application_timeline_events.FK_27860d3a56abb9d4d4d6e0802df:
--   application_id -> renewal_applications(id), DELETE RESTRICT, UPDATE NO ACTION
-- application_timeline_events.FK_7195522fa3d3188add4b021e132:
--   actor_user_id -> users(id), DELETE SET NULL, UPDATE NO ACTION

-- ---------------------------------------------------------------------------
-- Immutable-history database objects
-- ---------------------------------------------------------------------------
-- public.fn_guard_vehicle_classification_history and
-- trg_guard_vehicle_classification_history reject UPDATE and DELETE on
-- vehicle_classification_history.
-- public.fn_guard_renewal_application_status_history and
-- trg_guard_renewal_application_status_history_immutable reject UPDATE and
-- DELETE on renewal_application_status_history.
--
-- Migration 11 physical inspection objects
-- application_status adds INSPECTION_FAILED. inspections.attempt_number is
-- smallint NOT NULL with chk_inspections_attempt_number (IN (1, 2)) and
-- uq_inspections_application_attempt (application_id, attempt_number).
-- chk_inspections_state_consistency requires coherent PENDING/COMPLETED result,
-- recorder, completion and reason fields. chk_inspections_result_failure_reason
-- requires PASS reason NULL and FAIL a trimmed nonempty reason up to 500 chars.
-- public.fn_guard_completed_inspection_immutable and
-- trg_guard_completed_inspection_immutable reject UPDATE and DELETE of a
-- completed inspection. renewal_application_status_history.reason is
-- varchar(100). Migration 11 down is intentionally irreversible because enum
-- evolution cannot be safely reverted.
--
-- Migration 12 sticker objects
-- stickers has required application_id, inspection_id, sticker_number, and
-- issued_at. uq_stickers_application, uq_stickers_inspection, and
-- uq_stickers_sticker_number enforce one Sticker per application, successful
-- PASS inspection, and exact sticker number. The
-- chk_stickers_sticker_number_trimmed_nonempty check requires sticker_number to
-- be non-empty and already trimmed. idx_stickers_issued_at indexes issued_at.
-- The current Sticker FKs are fk_stickers_application, fk_stickers_inspection,
-- and fk_stickers_issued_by_user; the old persisted sticker state,
-- certificate, readiness, and pickup objects were removed with sticker_status.
